### PR TITLE
fix:Fix the residual problem after sheet creation fails

### PR DESCRIPTION
**Pull request by mahuifa**
Since ST_DialogSheet and ST_MacroSheet are not yet supported;
If ST_DialogSheet or ST_MacroSheet is created in Release mode, it will fail, and if Q_ASSERT fails in Release mode, it will cause sheetNames to add an uncreated sheetName;

### CODE REVIEW

**Comment by dantti** [comment]
Please fix your indentation.

**Comment by mahuifa** [comment]
It has been modified

**Comment by dantti** [comment]
did you close on purpose or hit the wrong button?

**Comment by mahuifa** [comment]
Although ST_DialogSheet or ST_MacroSheet is not yet supported, I want to test the consequences of incorrect use of ST_DialogSheet or ST_MacroSheet, and found that sheetNames adds an invalid sheetName;

**Comment by mahuifa** [comment]
Sorry, pressed the wrong close button

**Pull request merged**
