### PR TITLE
variable instead of hard-coded value

### PR DESCRIPTION
**Pull request by AndreiCherniaev**
I add changes like in example
QXlsx/Pump/CMakeLists.txt

P.S. Also we should think how fix [here](https://github.com/QtExcel/QXlsx/blob/master/HowToSetProject-cmake.md)
target_link_libraries(**myapp** PRIVATE QXlsx::QXlsx)

### CODE REVIEW

**Comment by dantti** [comment]
Sorry I don't see the value of this change

**Comment by AndreiCherniaev** [comment]
> Sorry I don't see the value of this change

Example should demonstrate good style of programming, isn't it? Hard-coded value is bad decision, ${PROJECT_NAME} is good.

**Comment by AndreiCherniaev** [comment]
@dantti @j2doll @DarthGandalf @MartinDelille  please check again my commit. I still think that QXlsx should use variable instead of hard-coded value!

**Comment by DarthGandalf** [comment]
I also don't see the value of this change.

This is just an example app. And not every app uses "project name" has "the executable name", and often there's more than one executable per project.

Examples should be clear. This example is clear as is, without obfuscating the important values behind many levels of indirection.

**Comment by AndreiCherniaev** [comment]
@dantti can you please make your own review for my commit please? I am still thinking that example should be very copy-past friendly...

@DarthGandalf "not every app uses "project name" has "the executable name"" - yes, not every app uses "project name", but usually never use "HelloWorld" like on example, isn't it? A lot of CMake dummers want QXlsx without time to learn CMake...

**Comment by dantti** [comment]
I already did my own review, you can contribute meaninful changes to this project, seems like you just want to be listed as a contributor.

**Comment by DarthGandalf** [comment]
> A lot of CMake dummers want QXlsx without time to learn CMake

You're exactly right!

And you know what, changing the string HelloWorld after the copypaste is much easier and more obvious, than to somehow know what this magic string ${PROJECT_NAME} does and where the value comes from.

**Pull request closed without merging**
