### PR TITLE
CMake: Allow for OPTIONAL shared lib build

### PR DESCRIPTION
**Pull request by dantti**
* Allow this project to be used with CMake FetchContent
 * Make sure only public headers are installed
 * Add support to generate packages with CPack
 * Set the proper targets/interfaces when used as shared library

Partially fixes ISSUE #49 as proper export symbols are needed

### CODE REVIEW

**Comment by Jihadist** [comment]
Why you decide to make it static by default?

**Comment by dantti** [comment]
To keep things working as before

**Comment by Jihadist** [comment]
I try to test your pr but catch error
```
include(FetchContent)

FetchContent_Declare(
  QXlsx
  GIT_REPOSITORY https://github.com/QtExcel/QXlsx.git
  GIT_TAG        0461eac843358aec56c648ec929ca20da5822fdc
  SOURCE_SUBDIR  QXlsx
)
FetchContent_MakeAvailable(QXlsx)
```
I made this, then try to ```find_package(QXlsx REQUIRED)``` and then i had error

>  By not providing "FindQXlsx.cmake" in CMAKE_MODULE_PATH this project has
>  asked CMake to find a package configuration file provided by "QXlsx", but
>   CMake did not find one.
> 
>   Could not find a package configuration file provided by "QXlsx" with any of
>   the following names:
> 
>     QXlsxConfig.cmake
>     qxlsx-config.cmake
> 
>   Add the installation prefix of "QXlsx" to CMAKE_PREFIX_PATH or set
>   "QXlsx_DIR" to a directory containing one of the above files.  If "QXlsx"
>   provides a separate development package or SDK, be sure it has been
>   installed.

It looks like something missed. What i do wrong?

**Comment by dantti** [comment]
When you use fetch content you don't use find package

**Comment by dantti** [comment]
Why I don't see this on master?

**Comment by MartinDelille** [comment]
Hi @j2doll,

I'm working on adding your library to the [Conan center index](https://github.com/conan-io/conan-center-index/pull/8941).
It would be nice to have this PR merged since it changes the `CMakeLists.txt` a lot.

Any idea why it has been removed from master ?

**Pull request merged**
